#!/bin/bash
#
# A simple command for AES-256 decryption of a file, using gpg

# Check if the correct number of arguments is passed
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <input_file> <output_file>"
    exit 1
fi

# Check if the input file exists
if [ ! -f "$1" ]; then
    echo "Error: The file '$1' does not exist."
    exit 1
fi

echo Decrypting "$1" into "$2" ...
gpg --output "$2" --verbose --decrypt "$1"
