#!/bin/bash
# 
# A script to install all software nesessary for working with hebrew
# 
aptitude update 
aptitude install openoffice.org-l10n-he -y
aptitude install hspell hspell-gui -y
aptitude install emacs-intl-fonts -y
aptitude install koffice-i18n-he -y
# Here you also should install hebrew fonts